/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111923-gfdd123de13-20230905"
#endif /* AVUTIL_FFVERSION_H */
